# Generated by Django 3.1.4 on 2021-01-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210118_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
